config/routes.rb
Rails.application.routes.draw do
  root 'rushes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rushes, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rush.rb
class Rush < ApplicationRecord
  NAME_ATTR_PAIRS = [
    ['Player', :name],
    ['Team', :team],
    ['Pos', :position],
    ['Att', :attempts],
    ['Att/G', :attempts_per_game],
    ['Yds', :yards],
    ['Avg', :avg_yards],
    ['Yds/G', :yards_per_game],
    ['TD', :touchdowns],
    ['Lng', :longest_rush],
    ['1st', :first_downs],
    ['1st%', :first_down_percent],
    ['20+', :over_20_yards],
    ['40+', :over_40_yards],
    ['FUM', :fumbles]
  ]
end

app/models/rush_importer.rb
module RushImporter
  def self.import(json_path)
    file = File.read(json_path)
    JSON.parse(file).each do |data|
      rush = Rush.new
      Rush::NAME_ATTR_PAIRS.each { |(name, attr)| rush[attr] = data[name] }
      rush.save!
    end
  end
end

app/models/rushes_service.rb
module RushesService
  PAGE_SIZE = 50

  def processed_rushes(params)
    rushes = Rush
    if params[:name]
      rushes = rushes.where('name like ?', "%#{params[:name]}%")
    end
    attr_exists =
      Rush::NAME_ATTR_PAIRS.select { |(_, attr)| params[:order_by] == attr.to_s }.present?
    if params[:order_by] && attr_exists
      rushes = rushes.order(params[:order_by] => params[:order])
    end
    return rushes
  end

  def paged_rushes(params, rushes)
    page = params[:page].to_i || 0
    rushes.limit(PAGE_SIZE).offset(page * PAGE_SIZE)
  end

  def page_metadata(params, rushes)
    page = params[:page].to_i || 0
    {
      page: page,
      remaining: (rushes.count - PAGE_SIZE * (page + 1))
    }
  end

  def to_csv(rushes)
    CSV.generate do |csv|
      csv << Rush::NAME_ATTR_PAIRS.map { |(a, _)| a }
      rushes.each do |rush|
        row = []
        Rush::NAME_ATTR_PAIRS.each do |_, attr|
          row << rush[attr]
        end
        csv << row
      end
    end
  end

  def order_param(params, attr)
    if params[:order_by] == attr.to_s
      params[:order] == 'asc' ? 'desc' : 'asc'
    else
      'desc'
    end
  end

  extend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rushes_controller.rb
require 'csv'

include RushesService

class RushesController < ApplicationController
  def index
    @index_params = params.permit(:order, :order_by, :name, :page)
    rushes = processed_rushes(@index_params)
    respond_to do |fmt|
      fmt.html do
        @page_metadata = page_metadata(@index_params, rushes)
        @rushes = paged_rushes(@index_params, rushes)
      end
      fmt.csv { render plain: to_csv(rushes.all) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thescore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/pure-min.css" />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rushes/index.html.erb
<h1>Rushing Stats</h1>
<%= form_tag(rushes_path(@index_params), method: :get) do %>
  <%= label_tag('Player Name:') %>
  <%= text_field_tag('name') %>
  <%= submit_tag('Search') %>
<%- end %>
<hr />
<table class="pure-table">
  <thead>
    <tr>
      <% Rush::NAME_ATTR_PAIRS.each do |title, attr| %>
        <% order = RushesService.order_param(@index_params, attr) %>
        <td><%= link_to(title, rushes_path(@index_params.merge(order_by: attr, order: order))) %></td>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @rushes.each do |rush| %>
      <tr>
        <% Rush::NAME_ATTR_PAIRS.each do |_, attr| %>
          <td><%= rush[attr] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% page = @page_metadata[:page] %>
<% remaining = @page_metadata[:remaining] %>
<%= link_to("<< prev", rushes_path(@index_params.merge(page: page - 1)), class: 'pure-button') if page > 0 %>
<%= link_to("next >>", rushes_path(@index_params.merge(page: page + 1)), class: 'pure-button') if remaining > 0 %>
<hr />
<%= link_to("Download CSV", rushes_path(@index_params.merge(format: 'csv')), class: 'pure-button') %>